// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: bb.proto

package bb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd int32  `protobuf:"varint,1,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	Id  int64  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Dta []byte `protobuf:"bytes,3,opt,name=Dta,proto3" json:"Dta,omitempty"`
}

func (x *Snap) Reset() {
	*x = Snap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Snap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snap) ProtoMessage() {}

func (x *Snap) ProtoReflect() protoreflect.Message {
	mi := &file_bb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snap.ProtoReflect.Descriptor instead.
func (*Snap) Descriptor() ([]byte, []int) {
	return file_bb_proto_rawDescGZIP(), []int{0}
}

func (x *Snap) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *Snap) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Snap) GetDta() []byte {
	if x != nil {
		return x.Dta
	}
	return nil
}

var File_bb_proto protoreflect.FileDescriptor

var file_bb_proto_rawDesc = []byte{
	0x0a, 0x08, 0x62, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x62, 0x62, 0x22, 0x3a,
	0x0a, 0x04, 0x53, 0x6e, 0x61, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x6d, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x6d, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x44, 0x74, 0x61, 0x32, 0x26, 0x0a, 0x02, 0x42, 0x62,
	0x12, 0x20, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x08, 0x2e, 0x62, 0x62, 0x2e, 0x53, 0x6e,
	0x61, 0x70, 0x1a, 0x08, 0x2e, 0x62, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x6c, 0x69, 0x62, 0x61, 0x2f, 0x62, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bb_proto_rawDescOnce sync.Once
	file_bb_proto_rawDescData = file_bb_proto_rawDesc
)

func file_bb_proto_rawDescGZIP() []byte {
	file_bb_proto_rawDescOnce.Do(func() {
		file_bb_proto_rawDescData = protoimpl.X.CompressGZIP(file_bb_proto_rawDescData)
	})
	return file_bb_proto_rawDescData
}

var file_bb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bb_proto_goTypes = []interface{}{
	(*Snap)(nil), // 0: bb.Snap
}
var file_bb_proto_depIdxs = []int32{
	0, // 0: bb.Bb.Chat:input_type -> bb.Snap
	0, // 1: bb.Bb.Chat:output_type -> bb.Snap
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bb_proto_init() }
func file_bb_proto_init() {
	if File_bb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Snap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bb_proto_goTypes,
		DependencyIndexes: file_bb_proto_depIdxs,
		MessageInfos:      file_bb_proto_msgTypes,
	}.Build()
	File_bb_proto = out.File
	file_bb_proto_rawDesc = nil
	file_bb_proto_goTypes = nil
	file_bb_proto_depIdxs = nil
}
